### ISSUE TITLE
Slider does not have signal "value-changed"

### ISSUE THREAD

**Issue by mokilcde** [aleho/gnome-shell-volume-mixer#102]
Hi!

I got the following message after updating to Gnome Shell version 3.33.90:
gnome-shell[2532]: Extension "gnome-shell-screenshot@ttll.de" had error: Error: No signal 'value-changed' on object 'Gjs_Slider'

<details>
  <summary>Here is the complete output</summary><p>

```
gnome-shell[2532]: Usage of object.actor is deprecated for PanelMenuButton#012get@resource:///org/gnome/shell/ui/environment.js:235:29#012Indicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/indicator.js:253:5#012_createIndicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:207:25#012_updateIndicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:224:7#012Extension@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:180:5#012enable@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:330:16#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:130:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:477:13#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:456:9#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:13#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:517:13#012init@resource:///org/gnome/shell/ui/extensionSystem.js:31:9#012_initializeUI@resource:///org/gnome/shell/ui/main.js:239:5#012start@resource:///org/gnome/shell/ui/main.js:139:5#012@<main>:1:31
gnome-shell[2532]: Usage of object.actor is deprecated for PanelMenuButton#012get@resource:///org/gnome/shell/ui/environment.js:235:29#012Indicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/indicator.js:254:5#012_createIndicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:207:25#012_updateIndicator@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:224:7#012Extension@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:180:5#012enable@/srv/home/michael/.local/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/extension.js:330:16#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:130:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:477:13#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:456:9#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:13#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:517:13#012init@resource:///org/gnome/shell/ui/extensionSystem.js:31:9#012_initializeUI@resource:///org/gnome/shell/ui/main.js:239:5#012start@resource:///org/gnome/shell/ui/main.js:139:5#012@<main>:1:31
gnome-shell[2532]: Extension "gnome-shell-screenshot@ttll.de" had error: Error: No signal 'value-changed' on object 'Gjs_Slider'
```

</p></details>

CU
Michael

**Comment by aleho** [comment]
This seems to be the output of a different extension, gnome-shell-screenshot.

**Comment by mokilcde** [comment]
Sorry! I send the wrong output. The other extension have the same problem.
gnome-shell[2532]: Extension "shell-volume-mixer@derhofbauer.at" had error: Error: No signal 'value-changed' on object 'Gjs_Slider'

Please reopen the issue again

Output
gnome-shell[2532]: Usage of object.actor is deprecated for Slider#012get@resource:///org/gnome/shell/ui/environment.js:235:29#012MasterMenuItem<@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/menuItem.js:71:9#012_init@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:226:21#012StreamSlider<@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:56:9#012@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:830:19#012_init@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/menu/menu.js:76:24#012Menu<@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/menu/menu.js:55:9#012Indicator<@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/menu/indicator.js:38:28#012replaceOriginal@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/extension.js:60:20#012enable@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/extension.js:53:9#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:130:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:477:13#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:456:9#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:13#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:517:13#012init@resource:///org/gnome/shell/ui/extensionSystem.js:31:9#012_initializeUI@resource:///org/gnome/shell/ui/main.js:239:5#012start@resource:///org/gnome/shell/ui/main.js:139:5#012@<main>:1:31
gnome-shell[2532]: Usage of object.actor is deprecated for Slider#012get@resource:///org/gnome/shell/ui/environment.js:235:29#012_init@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:233:9#012StreamSlider<@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:56:9#012@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/widget/volume.js:830:19#012_init@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/menu/menu.js:76:24#012Menu<@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/menu/menu.js:55:9#012Indicator<@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/lib/menu/indicator.js:38:28#012replaceOriginal@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/extension.js:60:20#012enable@/srv/home/michael/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/extension.js:53:9#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:130:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:477:13#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:456:9#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:13#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:517:13#012init@resource:///org/gnome/shell/ui/extensionSystem.js:31:9#012_initializeUI@resource:///org/gnome/shell/ui/main.js:239:5#012start@resource:///org/gnome/shell/ui/main.js:139:5#012@<main>:1:31
gnome-shell[2532]: Extension "shell-volume-mixer@derhofbauer.at" had error: Error: No signal 'value-changed' on object 'Gjs_Slider'
