### ISSUE TITLE
Error in gnome-shell 3.34

### ISSUE THREAD

**Issue by flittermice** [aleho/gnome-shell-volume-mixer#105]
For me, the extension stopped working in GNOME 3.34:
see https://pastebin.com/r1ewj6Kp

I think the problem lies here (besides, there are some deprecation warnings):
> JS ERROR: Extension shell-volume-mixer@derhofbauer.at: Error: No signal 'value-changed' on object 'Gjs_Slider'

**Comment by aleho** [comment]
It seems you're using an outdated version?

**Comment by flittermice** [comment]
Strange, strange. Maybe the Gnome Shell didn't pull the correct version. I had to manually install Version 27 on one of my PCs. On the other computer the correct version was installed after trying again at extension.gnome.org. So, I really had outdated versions running. Thanks!!! 
Will be closing this now.
