### ISSUE TITLE
Volume locks at 0 in third party apps.

### ISSUE THREAD

**Issue by ashtonx** [aleho/gnome-shell-volume-mixer#106]
After lowering volume in application, like spotify or youtube in browser to 0. it's impossible to change it back inside the same application.  It can only be changed in input list.

No issue after disabling the volume mixer shell extension.

I'm guessing there's some sort of volume locking happening when volume reaches zero/gets muted.

Gnome 3.34

**Comment by aleho** [comment]
Thanks for the report!

Wasn't sure whether this was broken on my pretty broken Debian machine or actually affecting everyone.
