### ISSUE TITLE
Broken: on Manjaro GNOME

### ISSUE THREAD

**Issue by derekagraham78** [aleho/gnome-shell-volume-mixer#109]
gnome-shell  1:3.34.0+163+g6a6d66486-0
The minute I did the update of the extension it broke. 

inxi -Fxzc0
``
 grahamd  ~  inxi -Fxzc0
System:
  Host: Skinner Kernel: 5.2.19-1-MANJARO x86_64 bits: 64 compiler: gcc 
  v: 9.1.0 Desktop: Gnome 3.34.0 Distro: Manjaro Linux 
Machine:
  Type: Desktop System: Dell product: OptiPlex 7010 v: 01 serial: <filter> 
  Mobo: Dell model: 0YXT71 v: A02 serial: <filter> UEFI: Dell v: A21 
  date: 12/21/2015 
Battery:
  Device-1: hidpp_battery_0 
  model: Logitech Wireless Illuminated Keyboard K800 
  charge: 100% (should be ignored) status: Discharging 
  Device-2: hidpp_battery_1 model: Logitech Wireless Mouse M510 
  charge: 55% (should be ignored) status: Discharging 
CPU:
  Topology: Quad Core model: Intel Core i5-3470 bits: 64 type: MCP 
  arch: Ivy Bridge rev: 9 L2 cache: 6144 KiB 
  flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 25549 
  Speed: 1606 MHz min/max: 1600/3600 MHz Core speeds (MHz): 1: 1596 2: 1596 
  3: 1596 4: 1596 
Graphics:
  Device-1: AMD Lexa PRO [Radeon 540/540X/550/550X / RX 540X/550/550X] 
  vendor: Micro-Star MSI driver: amdgpu v: kernel bus ID: 01:00.0 
  Display: x11 server: X.Org 1.20.5 driver: amdgpu 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Radeon 550 Series (POLARIS12 DRM 3.32.0 5.2.19-1-MANJARO 
  LLVM 8.0.1) 
  v: 4.5 Mesa 19.2.0 direct render: Yes 
Audio:
  Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Dell 
  driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
  Device-2: AMD Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X] 
  vendor: Micro-Star MSI driver: snd_hda_intel v: kernel bus ID: 01:00.1 
  Device-3: Logitech Headset H390 type: USB 
  driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-1.3:3 
  Sound Server: ALSA v: k5.2.19-1-MANJARO 
Network:
  Device-1: Intel 82579LM Gigabit Network vendor: Dell driver: e1000e 
  v: 3.2.6-k port: f040 bus ID: 00:19.0 
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:
  Local Storage: total: 480.22 GiB used: 185.91 GiB (38.7%) 
  ID-1: /dev/sda vendor: Western Digital model: WD5000AAKS-08V0A0 
  size: 465.76 GiB 
  ID-2: /dev/sdb type: USB vendor: SanDisk model: Cruzer Glide 
  size: 14.46 GiB 
Partition:
  ID-1: / size: 457.16 GiB used: 185.91 GiB (40.7%) fs: ext4 dev: /dev/sda2 
Sensors:
  System Temperatures: cpu: 36.0 C mobo: N/A gpu: amdgpu temp: 29 C 
  Fan Speeds (RPM): N/A gpu: amdgpu fan: 3013 
Info:
  Processes: 247 Uptime: 33m Memory: 7.74 GiB used: 3.16 GiB (40.8%) 
  Init: systemd Compilers: gcc: N/A Shell: bash v: 5.0.11 inxi: 3.0.36 
``

**Comment by aleho** [comment]
What version are you using? What is the actual log output?

**Comment by derekagraham78** [comment]
it resolved on its own, reboot and I reinstalled the app.

Thanks,
Derek Graham

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
