### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by hongyi-zhao** [aleho/gnome-shell-volume-mixer#110]
Hi,

I try to install this tool on my Ubuntu 19.10 as follows:

```
$ sudo apt-get build-dep pulseaudio npm
$ git clone https://github.com/aleho/gnome-shell-volume-mixer.git gnome-shell-volume-mixer.git
$ cd gnome-shell-volume-mixer.git
$ make
$ mkdir  ~/.local/share/gnome-shell/extensions
$ cp -r shell-volume-mixer@derhofbauer.at/  ~/.local/share/gnome-shell/extensions/

```

After the above steps, from where can I invoke the corresponding panel of this tool?

Regards

**Comment by aleho** [comment]
It replaces the volume section in the panel menu.

You'll have to restart gnome-shell (log-in) to see it applied.
