### ISSUE TITLE
Fails to start on gnome-shell 3.35

### ISSUE THREAD

**Issue by jdoe3** [aleho/gnome-shell-volume-mixer#111]
The following error message appears in the log:

```
Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
```

The error appears to originate from `indicator.js`. I attempted to fix it by wrapping class declarations for `Indicator` and `IndicatorExtension` in `GObject.registerClass()`. This makes the error message go away, but the extension remains non-functional.

**Comment by Myralllka** [comment]
hey, the same on Gnome 3.36

**Comment by MateuszKubuszok** [comment]
As a temporal workaround https://extensions.gnome.org/extension/906/sound-output-device-chooser/ offers some of the functions, though it is missing the ability to change volume, and its UI clutters menu more than Volume Mixer.

I would be happier with working Volume Mixer though.

**Comment by aleho** [comment]
Sorry for not answering sooner. I'm aware of that issue, and will fix it as soon as I can.

This normally either involves waiting for Debian to update or installing and testing inside a VM.

**Comment by Vash63** [comment]
> Sorry for not answering sooner. I'm aware of that issue, and will fix it as soon as I can.
> 
> This normally either involves waiting for Debian to update or installing and testing inside a VM.

Debian Sid, I hope? By the time Debian Bullseye releases most non-LTS users will be using Gnome 3.38.

**Comment by aleho** [comment]
Haha, no, not stable. This is reserved for my servers. :wink:

Please try the latest master / release. Might be working now but I'm still trying to identify all issues.

**Comment by aleho** [comment]
I'm still getting strange bugs (double icon, crashes) but nothing I can reproduce relieably.
