### ISSUE TITLE
Crash on lock in 3.36.2

### ISSUE THREAD

**Issue by dmp1ce** [aleho/gnome-shell-volume-mixer#117]
When I have 3.36.2 enabled and I lock my computer my session crashes and I have to log in again. I am also using Wayland and I'm on Arch Linux.

I'm happy to provide any debug information needed.

**Comment by aleho** [comment]
Thanks for the report!

I just noticed it myself today, took a while to find the culprit.

**Comment by aleho** [comment]
See also https://gitlab.gnome.org/GNOME/gnome-shell/issues/2584
