### ISSUE TITLE
Gnome-shell crash on session lock, or screen suspend

### ISSUE THREAD

**Issue by thepasto** [aleho/gnome-shell-volume-mixer#118]
Hi, thanks for your work, amazing extension!

I'm having a Gnome shell crash, with yout extension enabled,  everytime my screen try to suspend for inactivity. The same behaviour if i try to lock the session.
Here's journalctl output, i don't know if it can help, but if you need more, just ask!

Thanks

[gnome_crash.txt](https://github.com/aleho/gnome-shell-volume-mixer/files/4437844/gnome_crash.txt)

**Comment by aleho** [comment]
Duplicate of #117, actually a gnome-shell bug (triggered by other extensions as well).
