### ISSUE TITLE
Scrolling with Dash-to-panel

### ISSUE THREAD

**Issue by Amathadius** [aleho/gnome-shell-volume-mixer#119]
Scrolling on the volume icon with the scroll option to change the dash-to-panel workspace, since gnome 3.38, changes the workspace and changes the volume at the same time. 

Before, the volume changed without changing the workspace.

**Comment by aleho** [comment]
Not an actual bug in Volume Mixer, but a sub-optimal check in Dash-to-panel.

**Comment by Amathadius** [comment]
I understand, but it doesn't happen without gnome-shell-volume-mixer/with the base indicator.

**Comment by aleho** [comment]
Yes, because dash-to-panel specifically implements an exception for the stock volume indicator.

I've added a small workaround for the current release, but I'll not implement hacks specific to other extensions.
