### ISSUE TITLE
[feature request] Switch to mute unmute single Applikations

### ISSUE THREAD

**Issue by Wabuo** [aleho/gnome-shell-volume-mixer#12]
I miss an function to easily mute/unmute single applications to do that it would be grate to have an switch before/behind the slide.

**Comment by aleho** [comment]
Mute can be done by middle-clicking on a slider.

**Comment by Wabuo** [comment]
nice to know ... but maybe write that under the settings so others also will know =)

**Comment by aleho** [comment]
It's in the README. Everybody reads the README, right? :P
