### ISSUE TITLE
GNOME 3.38 support

### ISSUE THREAD

**Issue by mfvescovi** [aleho/gnome-shell-volume-mixer#127]
Hi!
I'd like to officially package your extension for Debian (since I use it daily) but GNOME 3.38 has entered unstable/sid just few days ago and the actual release is failing to work; so now I need to wait for a 3.38-compatible release.

Any chance to know if you're working on porting GSVM to v3.38?

Thanks in advance.

**Comment by luk1337** [comment]
@mfvescovi check the `wip` branch.

**Comment by mfvescovi** [comment]
> @mfvescovi check the `wip` branch.

OK, but usually we (in Debian) prefer an official release for packaging.
Thus, I'll wait for `wip` branch to be merged in master branch.

Thanks for the hint.

**Comment by aleho** [comment]
@mfvescovi I guess @luk1337 was referring to "if you're working on" which I can definitely answer with "yes, I'm working on it". :wink:
No ETA, but I guess I'll be able to finish it next week.

Thanks for your effort in porting, by the way. Are you planning on using a git repo downstream or do you want to contribute the Debian folder here?

**Comment by mfvescovi** [comment]
> Thanks for your effort in porting, by the way. Are you planning on using a git repo downstream or do you want to contribute the Debian folder here?

By policy, we usually keep debian packaging on an istitutional GitLab instance called [_salsa_](https://salsa.debian.org).
Actually, it wouldn't have much sense to maintain the debian/ folder here; given Debian is _root_ for many other derivative distros, the better approach is to keep it on salsa, anyway.

Cheers.

**Comment by aleho** [comment]
Sure, fine with me! Thanks for your packaging effort (being a Debian user for more than 15 years, I really appreciate all the work).

Latest release should work with 3.38.0.

**Comment by jacobmischka** [comment]
Confirming that building from source works, but for some reason the most recent release on extensions.gnome.org doesn't seem to be updated yet.

Thanks for your work!

**Comment by aleho** [comment]
The release on extensions.gnome.org is out of my control due to a pending review (https://extensions.gnome.org/review/).

They usually are pretty quick, but as volunteer work goes there's usually a day job demanding more attention than some community project.
