### ISSUE TITLE
No PipeWire support

### ISSUE THREAD

**Issue by xerz-one** [aleho/gnome-shell-volume-mixer#133]
When the system is using PipeWire as its audio server, regardless of whenever `pipewire-pulse` is installed, the extension is unable to run and stops itself. This is a compatibility issue to be regarded, as there is an ongoing push for PipeWire which includes default shipping on the next Fedora version.

This has been tested in Arch Linux, with GNOME 3.38.4 and PipeWire 0.3.23.

**Comment by aleho** [comment]
This extension doesn't do anything special in regards to accessing Pulseaudio. It either works or doesn't, but that's not up to me.

Moreover, Pipewire's Pulseaudio implementation is supposed to be a drop-in replacement. An application using Pulseaudio is supposed not to care about the server at all. So, even if I could add fixes for how I'm dealing with the server (which I can't) I really shouldn't.

Currently I'm using pipewire-pulse on Fedora and the extension behaves normally. There might be something broken with the Python script, but I still think this would be a bug in Pipewire.

Can you run the Python helper and provide it's output?

**Comment by xerz-one** [comment]
Running `pautils/cardinfo.py` merely returns `{}`, no additional error logs. Meanwhile, `pavucontrol` is able to see my devices just fine.
![Pavucontrol showing my sound cards](https://user-images.githubusercontent.com/2456419/110481466-82799300-80df-11eb-860d-095079490a6d.png)

**Comment by AlexWayfer** [comment]
I have such error after about 1 second of DE reload:

![image](https://user-images.githubusercontent.com/6510020/111295688-b95e2480-865c-11eb-99d5-5557880ae6ab.png)

`shell-volume-mixer@derhofbauer.at/pautils/cardinfo.py` also returns `{}`.

**Comment by Vash63** [comment]
I'm also seeing this. It should probably be reported with Pipewire though, not here. Has anyone done so yet?

**Comment by aleho** [comment]
I'd have reported this issue if only I knew what to report.

All PA commands via Python are working here (I'm using `feature/sinks-improvements` branch currently, but that shouldn't actually make a difference). Pipewire 0.3.23.

Don't know what's wrong with the setups where it's broken. Especially since if the PA calls fail there should be an error, normally.

The branch `feature/sinks-improvements` contains updates to card / sink data retrieval.
Could you try calling `DEBUG=1 ./shell-volume-mixer@derhofbauer.at/pautils/cardinfo.py` or `DEBUG=1 ./shell-volume-mixer@derhofbauer.at/pautils/sinkinfo.py` and paste the output here?

**Comment by Vash63** [comment]
Just `{}` again for DEBUG=1 on cardinfo.py. I don't have a sinkinfo.py in my install.

**Comment by aleho** [comment]
@Vash63 Please checkout this repo and try the branch `feature/sinks-improvements`. It has a new util to query both sinks and cards:

`DEBUG=1 ./shell-volume-mixer@derhofbauer.at/pautils/query.py cards`
`DEBUG=1 ./shell-volume-mixer@derhofbauer.at/pautils/query.py sinks`

**Comment by Vash63** [comment]
Both output the same:

```Querying details...
Requesting all available data
Query done
{}```

**Comment by aleho** [comment]
Sorry, I really don't know what to do here.

The helper clearly doesn't fail, so it can only handle the data it is provided by the libpulse bindings.
If there's no failure and no errors are being reported I'm pretty sure it's a system setup thing.

There's a libpulse import at the top of the introspected library:

```Python
try:
    lib = CDLL('libpulse.so.0')
except:
    lib = CDLL('libpulse.so')
```

Maybe your system path's are different?

Nevertheless, the pipewire-pulse implementation is supposed to provide a drop-in replacement. If it works in Pulseaudio it has to work in Pipewire.

---
`pactl info`:

```
…
Server Name: PulseAudio (on PipeWire 0.3.24)
Server Version: 14.0.0
…
```

`DEBUG=1 ./query.py cards`
```
Querying details...
Requesting all available data
In callback
Callback done
In callback
Callback done
In callback
Callback done
In callback
All done
Query done
{
    "46": {
        "index": 46,
        "alsaCard": 1,
        "name": "alsa_card.pci-0000_06_00.1",
        "description": "HD-Audio Generic",
        "active_profile": "off",
        "profiles": {
            "off": {
                "name": "off",
                "description": "Off",
                "available": true
            },
            "HiFi": {
                "name": "HiFi",
                "description": "Play HiFi quality Music",
                "available": false
            }
        },
        "ports": {
            "[Out] HDMI3": {
                "name": "[Out] HDMI3",
                "description": "HDMI3 Output",
                "direction": "out",
                "available": false
            },
            "[Out] HDMI2": {
                "name": "[Out] HDMI2",
                "description": "HDMI2 Output",
                "direction": "out",
                "available": false
            },
            "[Out] HDMI1": {
                "name": "[Out] HDMI1",
                "description": "HDMI1 Output",
                "direction": "out",
                "available": false
            }
        }
    }
}
…
```

**Comment by saivert** [comment]
The problem is that you loop for 1000 iterations but this isn't guaranteed to be enough to let everything initialize and connect. On my systems it sometimes returns all the card info and sometimes just "{}".

You need to use the event system in pulseaudio to check when it has actually connected.

But simply increasing the loops to 2000 or even higher may work but that is an ugly hack and you should fix your code.

**Comment by aleho** [comment]
The looping was there to stop it from running forever. Can't remember why I added it in the first place, that code is many years old.

**Comment by Vash63** [comment]
I can confirm the above patch fixes the python files for me. I can no longer test the extension proper as I've upgraded to Gnome 40, but both `./query.py cards` as well as `./query.py sinks` are now outputting my card/sink data.

**Comment by aleho** [comment]
Cool! I just pushed an update to the branch, this should fix it then.

**Comment by aleho** [comment]
@Vash63 As for Gnome 40: Don't know if this will happen soon here. There's a lot to adapt and test and I'm very busy at the moment.
