### ISSUE TITLE
Gnome 40 support

### ISSUE THREAD

**Issue by jacobmischka** [aleho/gnome-shell-volume-mixer#135]
Gnome 40 has been released!

I've added a few commits to my fork which fixes the main issues that need adjusting, in case it's useful by someone who's more familiar with the codebase when preparing a proper update: https://github.com/jacobmischka/gnome-shell-volume-mixer

Primary issues I've noticed that need to be addressed:

1. API call `getOutputIcon()` to get the volume menu icon doesn't exist anymore, replacing it fails (328a40915a97af47e73286e87b38c65d86349c76 and 16c61247604a372beca2fc57565cede9bbf8811c)
2. When switching profiles, the notification needs to display the profile description instead of the profile object (7dd364ac1406d44601f12693ce26d9caa6266d12)
3. Version number must be bumped, obviously (0fec2a0f1e6644f64cb4cdab4ccec2574a68b2a5)
4. Settings menu needs to be ported to gtk4 (I haven't attempted that, changing settings via dconf is a fine workaround for me for now)

Thankfully, everything else seems to still just work as far as I can tell in my daily use. If I find some free time soon I'll try to prepare a proper PR starting point for the fixes I listed, but for now I just wanted something running so they're mostly just quick hacks and not quality enough to merge into the extension.

Thanks again for this great extension!

**Comment by aleho** [comment]
Thanks for your help!

Please consider providing a PR next time. This make collaboration a lot easier.

In the end it turned out to be a lot more work than just a few fixes though, especially with settings.
