### ISSUE TITLE
Long device names are indistinguishable

### ISSUE THREAD

**Issue by juliatuttle** [aleho/gnome-shell-volume-mixer#140]
My laptop's internal sound card has a rather long name, and all of the sources and sinks it provides are prefixed with this name, so the various outputs are elided to an identical name and I can't tell them apart in the mixer:

![sinks](https://user-images.githubusercontent.com/403599/128644050-4fe2112e-7d2e-4ad1-8c92-2bfd03e20b18.png)

I can think of a few solutions, listed in the order I'd personally prefer them:

1. Let me give the outputs custom names in Settings, so I can rename "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI1 Output" to "Speakers" since that's where it goes.
2. Change how the names are elided in the mixer so I can see the end of the name. I think eliding in the middle would be preferable to eliding at the beginning, but I'm not sure.
3. Make the full names visible as a tooltip when I hover over the elided names.

Any of these would help me, but I think 2 would be the most user-friendly. I'd be happy to take a whack at implementing it if you'd like.

By the way, thanks for this extension; it's a necessary UI feature since I regularly switch between (at least) two audio outputs.

----

For context, here are the full lists of sources:

- Antlion USB adapter Mono
- HD Pro Webcam C920 Analog Stereo
- Monitor of Antlion USB adapter Analog Stereo
- Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI1 Output
- Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI2 Output
- Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller HDMI3 Output
- Monitor of Tiger Lake-LP Smart Sound Technology Audio Controller Speaker + Headphones
- Tiger Lake-LP Smart Sound Technology Audio Controller Digital Microphone
- Tiger Lake-LP Smart Sound Technology Audio Controller Headset Mono Microphone + Headphones Stereo Microphone

and sinks:

- Tiger Lake-LP Smart Sound Technology Audio Controller HDMI3 Output
- Tiger Lake-LP Smart Sound Technology Audio Controller HDMI2 Output
- Tiger Lake-LP Smart Sound Technology Audio Controller HDMI1 Output
- Tiger Lake-LP Smart Sound Technology Audio Controller Speaker + Headphones
- Antlion USB adapter Analog Stereo

on my laptop.

**Comment by vismajor1** [comment]
I have the same problem, so I will add some more information. I have the Thinkpad X1 Carbon gen 9. When i enter the command "pacmd list-sinks" I see all audio sinks. The long name comes from the device.profile.name = "HiFi: hw:sofhdadsp: sink" and device.description = "Tiger Lake-LP Smart Sound Technology Audio Controller Speaker + Headphones" . So the Extension uses the profil name to create the name. But in the line device.profile.description = "Speaker + Headphones" would be the more useful name. 
But I also didn't find the location in the Extension to change this.
![image](https://user-images.githubusercontent.com/63057057/165591193-43b5c9ae-2ab3-4f8e-b3e0-1309b34a87d0.png)

![image](https://user-images.githubusercontent.com/63057057/165591268-9d558789-984f-48de-b39e-940e6fa27011.png)

**Comment by aleho** [comment]
Sorry, I'm not going to fix any issues for older versions and reevaluate the use-case for this extension for 43.

**Comment by vismajor1** [comment]
So this will be fixed at gnome 43? Nice, thanks.

**Comment by aleho** [comment]
That depends on how GNOME 43 is actually going to implement that in the quick settings.

**Comment by vismajor1** [comment]
I understand. Thank you for the effort.

**Comment by aleho** [comment]
Just to be clear: if GNOME decides to implement it in a way I think I can improve with this extension I'll probably come up with a solution. Probably :D.

If they manage to provide everything I need I'll definitely stop trying to hack around and monkey patch layout issues and focus on the features that are actually useful.
