### ISSUE TITLE
Help with disabling switch beheaviour of output volume sliders

### ISSUE THREAD

**Issue by topotech** [aleho/gnome-shell-volume-mixer#150]
I need help with finding where in the code is set that clicking the output devices outside sliders changes the output device for all the streams.

Using the image as example: "Audio interno stereo analógico" (Built-in Audio Analog Stereo) and Bluetooth Music are the two available output devices, but when I clumsily miss the slider and click outside of it, the extension automatically sets all my streams to the selected output. I want to prevent that behaviour, but I'm not sure if that is set in lib/menu, lib/widget or any other place.

I usually use different outputs for different programs, so every time this happens, I must open pavucontrol and tweak all over again. Nothing hard, but I end up doing it about 6 times per day.
 
![imagen](https://user-images.githubusercontent.com/8272252/142444914-f0ef779b-849b-4de9-9632-1f1ab860c2ff.png)

**Comment by aleho** [comment]
Can you use the scroll-wheel, maybe?
