### ISSUE TITLE
error after the last update

### ISSUE THREAD

**Issue by preIdiot** [aleho/gnome-shell-volume-mixer#151]
I updated the extension yesterday and after that, it is giving an `error`. I tried reinstalling but it didn't help.
I am on Ubuntu 20.04.3, Gnome: 3.36.8

**Comment by aleho** [comment]
Please use 3.36.6 (https://github.com/aleho/gnome-shell-volume-mixer/releases/tag/3.36.6). Any other release could break.

**Comment by preIdiot** [comment]
working thanks!!
