### ISSUE TITLE
Extension makes assumation where python3 is located

### ISSUE THREAD

**Issue by rhoriguchi** [aleho/gnome-shell-volume-mixer#153]
This extension assumes that python is located under `/usr/bin/env`, which is not the case in all distros. It would be better to check all dirs in the environment variable `PATH`.

https://github.com/aleho/gnome-shell-volume-mixer/blob/b8b0bc58ec920432366fdfed365475e83e88cab9/shell-volume-mixer%40derhofbauer.at/lib/utils/paHelper.js#L28

https://github.com/aleho/gnome-shell-volume-mixer/blob/b8b0bc58ec920432366fdfed365475e83e88cab9/shell-volume-mixer%40derhofbauer.at/lib/utils/paHelper.js#L66

PR to patch this NixOS/nixpkgs#154692

**Comment by aleho** [comment]
That's actually incorrect.

Python is not located under `/usr/bin/env`, `env` is used to determine the location of the Python installation.
That's a standard way of determining the installation path in Linux.

I'm not going to implement work-arounds for broken setups via a custom PATH lookup for the few instances where `env` might not be available or point to the wrong Python executable.
