### ISSUE TITLE
Gnome 42 Compatability

### ISSUE THREAD

**Issue by mrenvoize** [aleho/gnome-shell-volume-mixer#154]
All appears to be working with the customary update to metadata.json.

**Comment by aleho** [comment]
Nope, cannot confirm. It seems horribly broken here.

**Comment by Ghibranalj** [comment]
~~It works perfectly without update using this command.~~
~~`gsettings set org.gnome.shell disable-extension-version-validation "true"`.~~
~~It seems to me that its just a configuration thing~~

edit:
Nvm its broken

**Comment by hchen98** [comment]
Any updates regarding this? I mean, Ubuntu 22.04 LTS was released yesterday with Gnome 42 tho...

**Comment by aleho** [comment]
I'm using Fedora.

**Comment by Spurlos** [comment]
> I'm using Fedora.

Fedora update to Gnome 42 is just around the corner, so this would be a wider compatibility issue eventually.
![image](https://user-images.githubusercontent.com/667533/165633313-9c112d43-37d5-414d-86e6-307e137027e9.png)

**Comment by mrenvoize** [comment]
Interesting, it all appeared to work OK in Arch when I updated.. but yes, I'm seeing issues in Ubuntu.  I see there's a branch where you're working on it which is great to see, thanks @aleho .

Shout if there's anything we can do to help

**Comment by jmico** [comment]
After editing metadata.json, the last published version of the extension (v. 44) works just fine on Ubuntu 22.04.1 which comes with Gnome 42.4 (besides speaker icon bugs).

**Comment by aleho** [comment]
I'm honestly not going to fix the bugs in 42. I already spent about 20 hours trying to find out why it's broken and couldn't fix it reliably.

With 43 they announced to add an output device selection, which means I'll have to rewrite the entire UI part anyway if I still see a use case for this extension at all.

**Comment by jmico** [comment]
I agree with your assessment. Thanks for your work!
