### ISSUE TITLE
Missing volume bar for active device when using start menu position in Gnome 42

### ISSUE THREAD

**Issue by MexHigh** [aleho/gnome-shell-volume-mixer#155]
## Description

I'm currently having the issue that the volume bar is not visible on the active device when using the start menu position. When using any other positioning that is not in the status bar, then it works as expected. This makes it impossible to adjust the current volume without switching between output devices.

Related: #154 

### Settings:
![image](https://user-images.githubusercontent.com/50419884/170825449-e3687c12-04b2-4932-a598-dcefa6074e6e.png)

### Start menu (collapsed volume mixer):
![image](https://user-images.githubusercontent.com/50419884/170825462-5a69b713-3daa-49bc-9f73-a95299ba3387.png)

### Start menu (expanded volume mixer):
![image](https://user-images.githubusercontent.com/50419884/170825485-3f3724c2-3ffd-4c2a-858c-e158c7ada42a.png)

### Volume mixer with position: right (working as expected):
![image](https://user-images.githubusercontent.com/50419884/170825538-6ebc9b49-b881-4c37-b3b7-cee36b8c61e5.png)

**Thanks for your help in advance :)**

**Comment by aleho** [comment]
Sorry, I'm not going to fix any bugs for GNOME 42 and reevaluate the use-case for this extension for 43.
