### ISSUE TITLE
Missing speaker icon after screen lock or reboot

### ISSUE THREAD

**Issue by MexHigh** [aleho/gnome-shell-volume-mixer#156]
## Description

Whenever I start my computer or unlock it after screen lock, the speaker icon is not visible in the top bar. Only when adjusting the volume via the volume bar, the icon does appear and stays visible until the next screen lock / reboot. 

This only applies when using the positions left, middle and right, not in the start menu.

I'm using Gnome 42.1.

Related #154 

### Icon after unlocking
![image](https://user-images.githubusercontent.com/50419884/170832073-be6343ae-4c2a-4107-bcfb-f685f1687ad1.png)

### Icon after adjusting the volume
![image](https://user-images.githubusercontent.com/50419884/170832079-26aa4851-f231-4026-bfe7-0337ad2dc32a.png)

**Comment by aleho** [comment]
Sorry, I'm not going to fix any bugs for GNOME 42 and reevaluate the use-case for this extension for 43.
