### ISSUE TITLE
Mouse wheel events over the speaker icon don't use custom volume step

### ISSUE THREAD

**Issue by kparal** [aleho/gnome-shell-volume-mixer#17]
The custom volume step applies to the volume slider and to multimedia keys, but it does not apply to scrolling the wheel over the speaker icon in top right corner - that still scrolls 10% up or down, regardless of the setting.

**Comment by aleho** [comment]
Didn't even know one could scroll over that icon to trigger volume change. :smile:

**Comment by kparal** [comment]
Works great, thanks. The tooltip is awesome. So many useful details which seem to be missing in the core gnome-shell.
