### ISSUE TITLE
GSD's hotkeys not grabed ?

### ISSUE THREAD

**Issue by Amxx** [aleho/gnome-shell-volume-mixer#18]
Hello
I have some issues with the extensions replacing the volume key's default actions.
Basically what happens is that the volume down key runs the extension, with the popup showing the volume % and a bar with values possibly over 100%, and when I press the volume up key I got the default gnome behaviour with the volume not being able to go over 100% and the anoying update sound

I guess the issue is with GSD's hotkeys not boing grabed. Is this issue known ? Is there any fix ?

**Comment by Amxx** [comment]
Solving this (until it fails again) can be done by disabling the extension, pressing volume up and volume down and then re enabling the extension

**Comment by aleho** [comment]
Please provide more data and maybe some logs.
E.g. "journalctl /usr/bin/gnome-session", distribution, GNOME version(s), other extensions, self-compiled packages, etc.

Btw, you either have to be using a custom volume step (not 6%) or volume boost enabled to get SVM to grab the media keys. Everything else would be a bug. ;)

**Comment by Amxx** [comment]
journalctl /usr/bin/gnome-session contains a LOT of things and I don't really know what i'm looking for ... any grep sugestion ?

my details :
archlinux with gnome shell 3.14.3-2, all packages have been installed using pacman/yaourt

my extensions:
- Barrery status
- Bumblebee indicator
- Caffeine
- Empathy button
- Gnome/tomboy integration
- Launch new instance
- Media player indicator
- Native window placement
- Removable drive menu
- Skype integration
- Systemmonirot
- Transmission daemon indicator
- User themes
- Volume mixer
- Weather
- Shellshape

My Volume mixer options are:
Position : Status Menu
Remove original slider : on
Show detailed slider : on
Use symbolic icons : off
Show system sound : on
Use volume boost : on
Volume Steps : 5%
No hotjey for profile switcher

**Comment by aleho** [comment]
Whoa, that's a lot of extensions.
There could be loads of possible interferences. Does the bug occur with all extensions but SVM enabled?

> journalctl /usr/bin/gnome-session contains a LOT of things

Restart Shell with all extensions disabled, run "journalctl -f /usr/bin/gnome-session".
Then enable only SVM. This should help a lot.

Could you also try to rebind the volume keys in the keyboard settings? I noticed that the defaults differ from the values being caught. Didn't cause any problems here, though.

**Comment by aleho** [comment]
Further discussions in #29 (as feedback was missing here).
