### ISSUE TITLE
Information on media player not updating.

### ISSUE THREAD

**Issue by joatmor** [aleho/gnome-shell-volume-mixer#19]
I use Rhythmbox along with two Gnome Shell Extensions - Media Player Indicator and Volume Mixer. Please note that I am running on Debian Jessie RC1 with Gnome Shell 3.14.1 and searching for usability bugs. In the area where Volume Mixer shows a slider for Rhythmbox it states the name of current song being played. Very nice. However, it does not update. Whenever I use Rhythmbox, Volume Mixer keeps indicating the first song I played. One thing to note is that the Media Player Indicator does update correctly. Also, I have the MediaServer2 D-Bus interface & the MPRIS D-Bus interface plugins for Rhythmbox enabled. All other plugins are disabled. Thank you for all you do.

Your Friend,

Len Huppe

![screenshot](https://cloud.githubusercontent.com/assets/8568835/6073714/3dcacb2c-ad80-11e4-856b-3a3dcfdb1062.png)

**Comment by aleho** [comment]
Yeah, I know about that problem.

Whenever Rhythmbox closes a stream and opens a new one everything is fine (like with manually selecting a song).

During Playback it just transitions to the next song and updates the stream info correctly (according to pavucontrol), but GSD doesn't provide any signals for stream updates.

There's just no simple way of knowing about stream updates at all (without patching GSD). I'll file a bug upstream, I guess.

**Comment by joatmor** [comment]
My apologies then for taking up your valuable time.

In times like this I wish that I had taken up software way back in 1980
instead of hardware. In that case I would be helping to create a patch
instead of informing you of a bug that you already know about. Nowadays I
am a health care worker and not much of software developer. However, I do
seen to have a knack for spotting usability issues in software systems. In
that case it is best that I try and spot them little buggers and raise a
warning flag when I do. As for Rhythmbox I do like it ,but the reality is
that it has some bugs. I really wish that I knew how to fix them.

Thank you for all that you do.

Your friend,

Len Huppe


On Sat, Feb 7, 2015 at 4:48 AM, Alexander Hofbauer <notifications@github.com

**Comment by aleho** [comment]
Nah, you don't have to worry about my time at all. That's just one of my pet projects I occasionally devote some hours to.

Btw, bug filed upstream at https://bugzilla.gnome.org/show_bug.cgi?id=744140

**Comment by aleho** [comment]
Patch got accepted upstream. Will take at least 3.20 to be in gnome-shell I guess.

**Comment by aleho** [comment]
Fixed some releases ago.
