### ISSUE TITLE
Switch input together with output

### ISSUE THREAD

**Issue by abrodkin** [aleho/gnome-shell-volume-mixer#20]
It's very convenient in some situations to switch input together with output.
For example if you want to use a headset, especially if there're options like:
1. Simple wired headset (plugged into audio jack)
2. USB headset

Probably this feature could be enabled through extension configuration because some people may have different usage scenario - for example have one and only microphone and switching from headphones to say HDMI output.

**Comment by jeukel** [comment]
Pleeeease :) :+1:

**Comment by aleho** [comment]
Sorry, I'm not going to fix any issues for older versions and reevaluate the use-case for this extension for 43.
