### ISSUE TITLE
unchained volume changes

### ISSUE THREAD

**Issue by OleksaBaida** [aleho/gnome-shell-volume-mixer#23]
in https://extensions.gnome.org/extension/212/advanced-volume-mixer/ when you change global soundcard's volume - app volume indication volume indication didn't change.

**Comment by aleho** [comment]
Don't know what you're talking about exactly, but if you change volume up on an output it is linked to all other outputs (proportionally).

As far as I remember, I didn't change that behavior in any way.

**Comment by derivator** [comment]
I think this might be referring to the [flat-volumes setting in pulseaudio](https://wiki.archlinux.org/index.php/PulseAudio#daemon.conf). The desired behaviour can be achieved by setting flat-volumes=no.
