### ISSUE TITLE
crash on gnome-shell 3.16

### ISSUE THREAD

**Issue by mirco** [aleho/gnome-shell-volume-mixer#24]
Hey
I know it's not released yet, but still as a heads up: the extension breaks on gnome-shell 3.16 (3.15.91 to be precise) with the following error in looking-glass:
TypeError: Shell.KeyBindingMode is undefined

**Comment by aleho** [comment]
Could you try the latest master version?

**Comment by mirco** [comment]
Yes it's fixed. Thanks
