### ISSUE TITLE
Use user defined lables for devices

### ISSUE THREAD

**Issue by aleho** [aleho/gnome-shell-volume-mixer#26]
See #7

**Comment by deBili** [comment]
thanks for looking at this. I've also noticed the icon you use for the OSD when switching cards is a bit different to the one shown when pressing the volume keys, which leads me to the conclusion that you could set different icons for different outputs. providing an option to label the device + to set a custom icon would be fantastic! not sure if it's possible to provide a different indicator icon on the panel for different cards too, that would be even more fantastic :)

**Comment by aleho** [comment]
Not going to happen as for now.
