### ISSUE TITLE
Volume keys get unbound sometimes

### ISSUE THREAD

**Issue by kparal** [aleho/gnome-shell-volume-mixer#29]
It happens to me that sometimes that volume down button gets unbound from volume-mixer and is handled by gnome-settings-daemon instead. That means that instead of lowering the volume by my configured amount (2%), it lowers it by default 6%, and emits a 'blop' sound on change. But volume up button is still handled by volume-mixer.

IIRC, this always affects just volume down, never volume up. Weird.

I have no idea how to reproduce it, it seems to occur randomly. It doesn't seem directly related to e.g. system start, resume or the like.

Do you have any idea what could be the cause and what to watch out for next time, so that we can find out what causes it?

I have the latest version from extensions.gnome.org for GNOME 3.14. I'm unsure how to find out the extension version. tweak-tools prints into terminal:

```
Apr 25 10:25:00 titan gnome-tweak-tool.desktop[4760]: INFO    : e.g.o no updates for shell-volume-mixer@derhofbauer.at (shell version 3.14.4 extension version unknown)
```

**Comment by kparal** [comment]
I happened just now, out of the blue. Just 10 minutes ago, both volume up and volume down buttons were handled by volume-mixer. But now, volume down is handled by g-s-d. I don't see anything related at all in system logs.

**Comment by kparal** [comment]
And now, during the same desktop session (no restart, no log out, nothing) the volume down button got rebound to volume-mixer and again works as expected. Again, I don't see anything useful in the logs. I was using Firefox the whole time, watching some youtube videos, but I don't know if that can be somehow related.

**Comment by aleho** [comment]
The extensions doesn't actively bind or grab hotkeys while running, only on startup.

I guess if gnome-settings-daemon restarts for some reason (like a crash) it will re-bind it's hotkeys and thus rendering volume-mixers tweaks useless. This doesn't happen to me here though (Debian unstable). At the moment I can't think of a way to prevent this.

**Comment by kparal** [comment]
I thought of that. But how is it possible that the problem "fixes itself" after a while sometimes, without restarting gnome-shell/extensions? I see nothing in the logs. And it seems to affect just volume down button. This is weird. I reported this mainly to see whether some other people chime in and report the same experience. If you don't see it yourself and there are no usable logs, I understand that you can't fix this.

Fedora 21

**Comment by aleho** [comment]
I can observe similar behavior with 3.16 from Debian/experimental. Once all necessary parts from 3.16 are in Debian I'll try to fix hotkey grabbing.

**Comment by kparal** [comment]
So unfortunately I experienced the same issue even on GNOME 3.18. Happened shortly after resume (I don't know whether directly after resume), but other resumes were fine. Will look for it further.

**Comment by kparal** [comment]
I've found out that if I keep restarting gnome-shell by `r` command, sometimes volume-mixer grabs the media buttons, sometimes it doesn't, and sometimes it grabs just one of them (volume up ungrabbed, volume down grabbed).

There seems to be a race condition during initialization. Maybe volume-mixer is sometimes faster than gnome-settings-daemon? And if either gnome-shell or gnome-settings-daemon get restarted (the user might not even notice), both or one of the buttons can get unbound?

**Comment by aleho** [comment]
Yes, this could be a race condition.

I'll add a timer to hotkey grabbing and see if I'll be able to trigger it.
Though, there have been reports that unbinds happen during a session. I'm not sure whether this is caused by settings-daemon crashing.

**Comment by aleho** [comment]
Lately, with Gnomw 3.26 (Xorg. not Wayland), I haven't seen any unbinding happen.

**Comment by kparal** [comment]
I see it occasionally as well (gnome 3.26, xorg, Fedora 27).

**Comment by orschiro** [comment]
I have the same setup as @kparal and see this too: https://youtu.be/95vUK2jdJ5k

**Comment by orschiro** [comment]
Sadly need to confirm that it's still happening with GNOME Shell 3.28.2. :-(

**Comment by ClarkWalker** [comment]
> Sadly need to confirm that it's still happening with GNOME Shell 3.28.2. :-(

I'm experiencing unbinds on 3.28.3, in Linux Mint 19.

**Comment by ClarkWalker** [comment]
I'm having a similar problem in GNOME shell 3.28.3 in Linux mint 19 Tara.  Sometimes when I start a session volume-up and/or volume-down will be unbound.  To be clear, I have never noticed losing a key binding mid-session.  My workaround for now has been to log out and back in until the key bindings are grabbed by gnome-shell-volume-mixer.  A race condition makes sense to me, I'll be experimenting with adding a timer to hotkey grabbing as well.

**Comment by orschiro** [comment]
Cool, thanks Alex! 🙂

-
