### ISSUE TITLE
Large number of audio streams makes menu unwieldy

### ISSUE THREAD

**Issue by derivator** [aleho/gnome-shell-volume-mixer#30]
I like having the volume mixer in the status menu, but since I usually have firefox open with a large number of tabs, with some of those tabs containing youtube videos, I get a lot of sliders named "CubebUtils | AudioStream". Since I also use the [media player indicator](https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer) extension, this can cause the power button at the bottom of the menu to go outside the screen boundary. This also causes the device selection menu to not expand correctly when clicked. While this should probably be addressed in gnome, it would be nice if we could have some kind of blacklisting capability to suppress (or collapse into a menu) sliders we don't need.

**Comment by aleho** [comment]
Fixed with 85c3ce98d48dce65590cb2703f409792f86e41ad, see also #40.
