### ISSUE TITLE
Volume slider goes beyond the edge of the menu

### ISSUE THREAD

**Issue by axelsimon** [aleho/gnome-shell-volume-mixer#31]
Hello,

As show in the attached screenshot, the volume slider expands beyond the edge of the menu (and outside the screen actually).

Running Gnome 3.14.1 on Debian GNU/Linux 8 (jessie) 64-bit.
Gnome-shell-volume-mixer is latest version from extensions.gnome.org

![menu_056](https://cloud.githubusercontent.com/assets/1172256/7768471/8eed18d6-007b-11e5-9811-a25f1f8b0c24.png)

Hope this helps!

Thanks

axel

**Comment by aleho** [comment]
This is strange. I am using Debian, never saw something like that.

Are you using any customizations, like a theme?

**Comment by axelsimon** [comment]
Sorry I never answered this… yes, I was using a theme I think at the time. I'd be hard pressed to tell you which one unfortunately. Not very helpful, I know.
Didn't see the issue when I later changed theme, so it was likely a specific occurrence.
