### ISSUE TITLE
Plugin is not loading on Ubuntu 15.04

### ISSUE THREAD

**Issue by alessandrolattao** [aleho/gnome-shell-volume-mixer#33]
Looking glass says "Error: invalid element in string array". 
I don't know how to help more :)

**Comment by aleho** [comment]
Does it give any detailed source code information? "Module", line number, etc, could be useful.

**Comment by VoidChen** [comment]
I have same problem on Debian stretch (gnome-shell 3.16.2-4).

I do some debug and found that error caused by `hotkeys.js`

    _proxyStringSettingChange: function(gsettings, key) {
        let value = gsettings.get_string(key) || undefined;
        let proxy = this._settings.get_array(key);

        // don't trigger a change event
        if (proxy.length == 1 && proxy[0] == value) {
            return;
        }

        this._settings.set_array(key, [value]);
    },
    
If `value` is undefined, the line `this._settings.set_array(key, [value]);` will cause error.
