### ISSUE TITLE
When using Volume Boost  the OSD struggles to find it's shape (Gnome Shell 3.16, Manjaro)

### ISSUE THREAD

**Issue by cyberalex4life** [aleho/gnome-shell-volume-mixer#35]
I usually change volume with mouse through easystroke (pressing right mouse button and scrolling one unit sends VolumeUp or VolumeDown (Fn combination keys). Because this happens usually very fast, when I use Volume Boost, the OSD goes at first wider than the resize reaches the final state (your settings I think). Sometimes it doesn't get to your dimensions on width and so they remain while changing the volume and until after the volume OSD dissapears. 
PS: the problem is on width!

**Comment by cyberalex4life** [comment]
![screenshot from 2015-07-25 16-32-17](https://cloud.githubusercontent.com/assets/2423189/8889634/63937232-32eb-11e5-8da9-0f6902398675.png)
![screenshot from 2015-07-25 16-36-36](https://cloud.githubusercontent.com/assets/2423189/8889635/65496ee2-32eb-11e5-844d-f40293750fd5.png)

**Comment by cyberalex4life** [comment]
ok, so some time after presenting this to you, I found a setting in dconf-editor (I was looking for something else): disable-workarounds. I checked that and things started moving a bit faster, and these things seized to happen (almost never). Then, this morning I disabled it, and these things also not happen anymore. Something that still happens is that, when I restart gnome-shell (Alt+F2-> type 'r' -> Enter), when making volume down, the volume OSD is without the percentage, and when making volume go up, the percentage appears and the OSD resizes. This gets fixed by disabling the extension in gnome-tweak-tool, then reenabling it.

**Comment by cyberalex4life** [comment]
gnome-shell 3.16 has on this distro some effects glitches: when I move the cursor to top of the screen to go to overlay and immediately moving it to the center of the screen, placing mouse over the area on which the transitions happen, these transitions freeze, then, if moving away the cursor, the transitions come to their end I'm saying this because it might explain the "bug"/glitch I reported (maybe it's not a bug from your extension). Another thing I did I installed another extension (SystemMonitor).

**Comment by aleho** [comment]
This is not related to any rendering problems but rather a key-grabbing issue I think.

For some reason since 3.16 the shell (or whoever is responsible) grabs media keys occasionally, taking it away from GSVM which is pretty problematic. I've got a workaround in mind, just haven't found the time to try implementing it.

Maybe in the next few days.

**Comment by cyberalex4life** [comment]
Advanced Volume Mixer still works nice...

**Comment by aleho** [comment]
It doesn't try to grab the volume overlay to override it for volume boost (percentage display above 100%).

**Comment by cyberalex4life** [comment]
I did those changes in mixer.js to _showVolumeOsd:
 _showVolumeOsd: function(level, percent) {
        let monitor = -1;
        let label = [];
        let n;

        if (level === 0) {
            n = 0;
        } else {
            n = parseInt(3 * percent / 100 + 1);
            n = Math.max(1, n);
            n = Math.min(3, n);
        }
/*
        if (this._defaultSink) {
            let port = this._defaultSink.get_port();
            if (port.port != 'analog-output-speaker'
                    && port.port != 'analog-output') {
                label.push(port.human_port);
            }
        }
*/
		let port = this._defaultSink.get_port();
		label.push(port.human_port);
/*
        if (this.boostVolume) {
            if (percent > 0) {
                label.push(percent + '%');
            } else {
                label.push(' ');
            }
        }
*/
        let icon = Gio.Icon.new_for_string(VOL_ICONS[n]);

        label = label.join('\n');
        if (!label) {
            label = null;
        }

        Main.osdWindowManager.show(monitor, icon, label, level);
    }
});

and commented //this._showVolumeInfo(percent, event)  - line 315 of _sliderChanged  to make the extension behave consistent. 
The extension works without any glitches, boost works also (percent not showing). My guess that mecanism of showing the OSD is inconsistent, maybe setting an OSD template once the extension is activated (template: OSD with the 2 lines: percentage and human_port).

**Comment by cyberalex4life** [comment]
choosing to show the percentage without the Port Name also works nice.

**Comment by aleho** [comment]
Is this still an issues? If so, please let me know and I'll reopen this bug.
