### ISSUE TITLE
Update for GNOME 3.18

### ISSUE THREAD

**Issue by kparal** [aleho/gnome-shell-volume-mixer#37]
Hello,

GNOME 3.18 has been released and many people already use it. Could you please update your extension at extensions.gnome.org to support this new GNOME version?

Thanks!

**Comment by aleho** [comment]
Basic functionality of this extension was already broken with 3.16, as there was no way to grab volume key changes.

Until I can upgrade, test and probably fix that, even if it's only for 3.18, I won't mark this extension compatible. It is broken after all (which makes me sad).

**Comment by kparal** [comment]
Which bug is that? I've been using it on 3.16 and I haven't noticed any issues.

**Comment by aleho** [comment]
Volume keys are grabbed by the system randomly. Haven't figured out how to exactly trigger it, but happens here all the time. Breaks custom volume steps and other functionality.

Worked perfectly in 3.14, so this likely was a problem introduced in 3.16. I wanted to provide a simple demo-extension for the devs and ask for their input. Haven't got the time to do that and now since 3.18 is out I'll have to verify this bug again.

**Comment by kparal** [comment]
I see. Yes, that has been happening from time to time, that's #29. However, that does not mean your extension is completely broken. If it stops working from time to time, but works most of the time, it's still better than when I can't use it at all. It's better to have improved functionality 90% of time than 0% of time. I would still recommend to enable your extension for 3.16 even though it does not work perfectly.

I [disabled version checking](http://worldofgnome.org/an-easy-way-to-test-extensions-compatibility-in-gnome-3-12/) in 3.18 and your extension seems to be still working (it uses custom volume steps, it shows individual applications volume sliders). I noticed #36, but that's just a visual glitch. I'll be able to tell you whether #29 is still happening after I use it for some time. Again, it's better to have something than nothing, so I'd again propose enabling this extension for 3.18, even though it's not perfect.

Thanks for your work.

**Comment by aleho** [comment]
If you could report back on key bindings being broken for you, that would be great!

Still waiting for Debian to migrate to 3.18. Maybe going to set up a Fedora / Gnome OS VM in the next few days.

**Comment by Bob131** [comment]
Just adding "3.18" to the metadata.json nets me with an odd visual artefact too:

![volume_mixer](https://cloud.githubusercontent.com/assets/4337852/10265138/386c649a-6a6f-11e5-9f57-b071b5b0f41e.png)

The slider seems to run of the end of the screen, in my case onto another monitor

**Comment by kparal** [comment]
@Bob131: That's #31 and #36.

I've been using this extension for just a few days now, but I haven't yet seen #29. Fingers crossed.
