### ISSUE TITLE
No signal "stream-changed" on object "GvcMixerControl"

### ISSUE THREAD

**Issue by alyst** [aleho/gnome-shell-volume-mixer#47]
I know that the recent commit requires that libgnome-volume-control is patched to support "stream-changed" event.
The commit message says that it is fixed in Gnome 3.20, but I have it installed (ArchLinux) and yet see this error message (%subj) in the gnome shell debugger.

**Comment by aleho** [comment]
You're right. I completely missed that its only in the library and wasn't updated in shell's submodules.

I can't tell how how disappointed I'm by the pace Gnome's development has taken. Three releases and no changes in sight, I'm on the edge of giving up.

**Comment by Gert-dev** [comment]
Might I humbly suggest, if possible, some kind of try-catch or "enable if present" behavior so at least the extension keeps working (but without the new behavior)?

**Comment by aleho** [comment]
I'm always happy about good pull requests.
You could also use the previous release, there's not much that has changed at all.
