### ISSUE TITLE
Change device name

### ISSUE THREAD

**Issue by roumano** [aleho/gnome-shell-volume-mixer#48]
Hi,

I would like a option to change device name

for exemple, i have enable 3 differents output 
- via hdmi (speaker of the screen)
- via my sound blaster and optical output to my hifi
- via usb earphone

I'm a geek, so i'm easy known/understand/remenber Sound Blaster is for hifi, hdmi for output to the screen , ...

but for my wife or someelse it's much more complex for them to understand

So i would like a option to be able to rename output device.

**Comment by aleho** [comment]
This is a path I'm actually not willing to go down (remembering labels, storing them, etc.).
Feel free to provide a patch though!
