### ISSUE TITLE
Collapsable mixer has hardcoded width

### ISSUE THREAD

**Issue by urandom** [aleho/gnome-shell-volume-mixer#50]
It seems the collapsable mixer part (the one that's clickable and shows you the different output sinks) has a hardcoded width that matches the default theme. On many other themes, the control is either longer or shorter than all other controls in the status menu. Such themes include Arc and Adapta. This is with gnome 3.20

**Comment by cyberalex4life** [comment]
I don't think so, after watching the changes from version to version, there is probably a commit error: 
the first two line in the .css file must be:
```
.masterslider .masterlabel,
.masterslider .slider {
    width: <your value>px;
}
```
Just delete **.smaller**. It works for me.
