### ISSUE TITLE
Text in the floating label not visible with custom theme

### ISSUE THREAD

**Issue by juliandroid** [aleho/gnome-shell-volume-mixer#51]
I'm using different than the default shell theme. In my case the theme is Flat-Plat, which is light instead of the default dark theme.
The problem is that you are not using both background color and the text color from currently active shell theme. You are setting:
$HOME/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/stylesheet.css

```
.floating-label {
    background-color: rgba(0, 0, 0, 0.9);
}
```

But the default text color for my light theme (Flat-Plat) is black too, so I end up with black floating label on black background.

My initial workaround was to set rgba(250, 250, 250, 0.9) but that will work only for me, then I decided to totally remove the .floating-label class!

The best approach is to use both (text and background) colors - the default for the theme or to overwrite them in your stylesheet.css (if you can't make it work).

**Comment by AlexWayfer** [comment]
I'm using `Milky` theme and have same problem.
