### ISSUE TITLE
Support gnome-shell 3.22

### ISSUE THREAD

**Issue by crayxt** [aleho/gnome-shell-volume-mixer#54]
I tried installing in Fedora 25 and it seems like gnome-shell 3.22 (3.21 atm) is not supported.

**Comment by crayxt** [comment]
Perfect!

**Comment by crayxt** [comment]
Somehow gnome-shell 3.21 in Fedora 25 Alpha still says extension does not support this shell version. Any more info I could provide?

**Comment by theangryangel** [comment]
@crayxt try adding 3.21 to this line https://github.com/aleho/gnome-shell-volume-mixer/blob/master/shell-volume-mixer%40derhofbauer.at/metadata.json#L6 in your checked out version.
