### ISSUE TITLE
Add Volume Boost toggle in the tray

### ISSUE THREAD

**Issue by elmagio** [aleho/gnome-shell-volume-mixer#55]
Hi, I opened an issue a while ago about the fact that every other boot the Volume Boost option would be disabled and I would need to go the extensions' settings and toggle it off and on again for it to work.

You answered that it was a bug that couldn't be fixed, which is fair enough, but it would go a great deal to reduce the impact of the issue there was an option to have the Volume Boost toggle directly in the tray, beneath the volume sliders. It could be fixed in two or three clicks of a mouse instead of the tedious process of going in the Tweak Tool, to the extensions tab, to the Volume Mixer settings and then back.

Thanks in advance for your answer.

**Comment by jacobmischka** [comment]
I would actually like this too. I usually don't want the boost option enabled, but occasionally there's an application I want to boost, so I would like to be able to easily enable the option when that happens.

**Comment by jacobmischka** [comment]
I took a crack at this, and it's pretty simple to add a switch that toggles the setting, but every time the setting changes it looks like the entire menu gets recreated, creating a new space above and leaving the now empty entry section still there.

The empty entry sections get removed when you close the menu, but it means toggling the setting looks odd until you close and reopen the menu again.

Not sure how to fix this.

![image](https://cloud.githubusercontent.com/assets/3939997/19822420/fbef4666-9d28-11e6-8fec-5363b052aa5f.png)

**Comment by elmagio** [comment]
@jacobmischka Maybe putting the switch inside the dropdown menu, instead as in its own entry in the  menu would fix this? 

In case I'm not clear, I mean putting it there:
![capture d ecran de 2016-10-29 09-53-53](https://cloud.githubusercontent.com/assets/14126056/19828109/ce604e58-9dbd-11e6-8863-0dd0c6ad4651.png)

**Comment by jacobmischka** [comment]
I don't think that will fix this problem, but admittedly I haven't taken the time to try.

**Comment by aleho** [comment]
Another input element in that already cluttered menu doesn't seem to be a good idea to me. Additionally, it wouldn't track the correct state of volume boost, as there's no way to know whether the system removed the keybinding in the meantime.

Anyway, as of current Gnome 3.26 (Debian), I don't seem to be getting unbinds, so I guess this problem might be "fixed".
