### ISSUE TITLE
On-screen indication when increasing and decreasing volume

### ISSUE THREAD

**Issue by Shamaoke** [aleho/gnome-shell-volume-mixer#57]
When increasing and decreasing volume by using hotkeys the volume on-screen [indication](http://i.imgur.com/zizImcR.png) isn't shown up.

GNOME 3.22.1; gnome-shell-volume-mixer git-4fc0647

**Comment by aleho** [comment]
Are you referring to #29?

**Comment by Shamaoke** [comment]
When I press my laptop's media keys for increasing or decreasing sound (Fn+F2, Fn+F3) and the extension is active, the corresponding OSD [indicator](http://i.imgur.com/zizImcR.png) — a white sound speaker in a black square — doesn't appear. The sound itself is decreased and increased without any issues. When the extension is deactivated, the indicator starts to appear.

**Comment by aleho** [comment]
Interesting. So for some reason, the OSD cannot be shown (which, frankly is a hack anyway).

Can't reproduce here though.

**Comment by Shamaoke** [comment]
Also, I want to add that this issue doesn't affect on other indicators: brightness, touch bar etc. They work as expected. Currently I'm on GNOME 3.24. The bug didn't disappear with the DE update.

**Comment by Shamaoke** [comment]
OK, I got the reason. If the volume step you set in preferences is less then 6, then the indicator stops to appear.
