### ISSUE TITLE
"update available"

### ISSUE THREAD

**Issue by caseyjp11** [aleho/gnome-shell-volume-mixer#58]
I posted this via the extensions site, and I don't know if this is mixer's fault or not, but it is the only extension doing this: Every few hours or so I get reminded that there is an update for volume mixer...only there never is.
All other "update" info is correct for all other extensions.

Because it is the ONLY extension with this, I figure it can't hurt to toss the info here as well.

I'm using archlinux (latest updates) and chromium with the git addon for gnome extensions. (I thought it might be this, but no errors are thrown, and all other extensions are reported correctly when they have updates available.)

**Comment by aleho** [comment]
Hmm, that's indeed strange. I'm getting the same update icon though.

Maybe it's related to the local git checkout. Not sure though.

**Comment by caseyjp11** [comment]
This no longer occurs, so closing this.

**Comment by caseyjp11** [comment]
No longer seeing this occur. Closing.
