### ISSUE TITLE
No boost settings available

### ISSUE THREAD

**Issue by UncleGoogle** [aleho/gnome-shell-volume-mixer#60]
Hi! I've installed your extension for volume boost feature but actually, there is no such thing. Have you idea why? Need I other software?

![screenshot from 2017-01-16 11-25-30](https://cloud.githubusercontent.com/assets/12197825/21979338/cb14dbec-dbde-11e6-9f30-77e805fab2cf.png)

gnome-shell 3.16.4
opensuse leap 42-1
Audio Controllers: Broadwell-U _and_ Wildcat Point-LP High Definition

**Comment by jacobmischka** [comment]
If you open the extension settings in Gnome Tweak Tool, you can toggle on "Use volume boost". That essentially just makes each volume slider move from 0% to around 153%, so you can use the slider to boost the volume.

![image](https://cloud.githubusercontent.com/assets/3939997/21987561/b1253390-dbc9-11e6-8062-d87cac080186.png)

**Comment by jacobmischka** [comment]
It's worth mentioning that this functionality is directly baked into pulseaudio and its GUI PulseAudio Volume Control, so you don't necessarily need this package to do it, it just makes it more convenient.

![image](https://cloud.githubusercontent.com/assets/3939997/21987621/e59d07a6-dbc9-11e6-8307-47fcb490a7b6.png)

**Comment by UncleGoogle** [comment]
Thanks!

**Comment by aleho** [comment]
Please also note that volume boost (and keyboard support for it) are directly related to grabbing keyboard shortcuts, which sadly doesn't work reliably any more for reasons unknown.

To make it work Gnome devs would have to care about input from extension devs, but I never got the impression that they actually did (nobody ever answered my questions).
