### ISSUE TITLE
Shortcut switch ignores USB sound card

### ISSUE THREAD

**Issue by corebots** [aleho/gnome-shell-volume-mixer#66]
My USB sound card is listed as output and can be added to the right side of the list in the _Devices_ tab but sound doesn't switch to it when i press the shortcut. 

It's a PCM Audio CODEC (Tascam US-100) on Fedora 26 (but was the same on previous Fedora versions). 

The audio switches _from_ the sound card, but not _to_ it . The OSD for the switch keeps appearing but nothing happens anymore. The sound card name has been changed to a user readable form previously via pavucontrol if that matters. 

Please what could i try to fix it?

Thank you so much for this extension, i use it daily :)

**Comment by corebots** [comment]
Anyone from the developers, please?

**Comment by aleho** [comment]
One developer, no reply. If you ask why: I don't have your specific USB device to test and even if I had there's no guarantee I could reproduce that problem.

**Comment by corebots** [comment]
But maybe, as the only developer, you have some suggestions on what could i try to troubleshoot?

**Comment by aleho** [comment]
Only one suggestion, from one developer: Try to find out whether this is something that has to do with your specific setup, then try to fix it and submit a pull request.

**Comment by aleho** [comment]
No feedback from bug author.

**Comment by corebots** [comment]
Thank you for the suggestion but I'm not a programmer, obviously as a regular user I don't know how to submit a pull request either. I don't know how to find out if it has to do with my specific setup - will it help if I plug the USB sound card into another PC with GNOME and your extension in use? I was thinking you could suggest some commands which I could run and and provide you the output so you have a better picture of why your extension causes this bug. Please reopen as issue remains even on latest Fedora 27 with GNOME 3.26.1.
