### ISSUE TITLE
Conflicts with other audio device selection extensions

### ISSUE THREAD

**Issue by Enigma0** [aleho/gnome-shell-volume-mixer#67]
It seems to replace all of the audio extensions that are in the menu popup.

**Comment by sonejizrelax** [comment]
Alt-F2 r

**Comment by aleho** [comment]
You mean it does the same thing as other extensions and therefore doesn't return to the previous state on unbind?

The problem here seems to be that apparently "other extensions" (whichever they might be), monkey-patch the same UI elements. There's not a lot I could do about this.

**Comment by Enigma0** [comment]
Yeah possibly. I no longer have a need to use potentially conflicting extensions so I'll close.
