### ISSUE TITLE
volume boost doesnt work with volume up shortcut

### ISSUE THREAD

**Issue by sonejizrelax** [aleho/gnome-shell-volume-mixer#68]
When i try to do volume up with my keyboard shortcut or my dedicated hardware button, it uses the default gnome-shell OSD and stops at 100%, but when i use volume down, the extension version of the OSD comes up showing the percentage and everything. This results in me not being able to use any keyboard shortcut to raise volume above 100% (the reason i installed the extension lol)

Sorry i only realised this only occurs with bluetooth speakers

**Comment by sonejizrelax** [comment]
somehow, it managed to fix itself wow lol

**Comment by AlexWayfer** [comment]
This occurs periodically even without a boost :confused:

**Comment by aleho** [comment]
Yeah, that's a Gnome "problem".

No Gnome dev ever answered my questions, so I stopped investigation - especially because it worked some versions ago and then they made changes I could not identify which broke grabbing of shortcuts. Basically I gave up.

See #29.
