### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Janvitus** [aleho/gnome-shell-volume-mixer#77]
Hello, I'am a translator of the GNOME italian team and I have translate your extension :)
[gnome-shell-volume-mixer.it.zip](https://github.com/aleho/gnome-shell-volume-mixer/files/1509279/gnome-shell-volume-mixer.it.zip)

**Comment by aleho** [comment]
Thanks!

If you want to, you can be added to the Crowdin Project (I can add you directly or you can find it under the name "GNOME Shell Volume Mixer").
