### ISSUE TITLE
Discrepancy between media keys to increase and decrease

### ISSUE THREAD

**Issue by orschiro** [aleho/gnome-shell-volume-mixer#80]
Hey @aleho,

Really nice extension. Thank you for your work on this!

I just noticed that the media keys on my keyboard have different behaviours. 

Going up suchs a percentage but not "plop" sound when increasing. 

Going down shows no percentage but has this "plop" sound when decreasing. 

Tested on Fedora 27. 

Also take a look at this screencast: https://youtu.be/95vUK2jdJ5k

**Comment by orschiro** [comment]
@AlexWayfer thanks! Shall we close this one then?

**Comment by AlexWayfer** [comment]
If you really have problems from #29, then it make no sense to leave this issue open. You can add details to the original issue from your case, if there is something specific and new. Your screencast, for example.
