### ISSUE TITLE
Incompatibilty with "Extend Panel Menu" extension

### ISSUE THREAD

**Issue by thunderschnozzle** [aleho/gnome-shell-volume-mixer#82]
I wanted to combine this extension with the "Extend Panel Menu" extension. However, there is a weird bug. It seems that if I enable the "Volume Mixer" extension with "Position of volume mixer" set to "Status Menu", it causes both the volume indicator's icon and the volume slider within it to disappear (the volume indicator is still there though). Basically there is a volume indicator with only volume settings and no icon.

The problem doesn't seem to occur with the "Audio Output Switcher", "Advanced Volume Mixer", or  "Sound Input & Output Device Chooser" extensions, which is weird.

Any idea what could cause this?

**Comment by aleho** [comment]
Works for me, just tried Extend Panel Menu on 3.32.
