### ISSUE TITLE
Input panel indentation a little wonky on 3.28

### ISSUE THREAD

**Issue by jacobmischka** [aleho/gnome-shell-volume-mixer#84]
It looks like Gnome increased the default indentation for the extended list items in 3.28. I think we should remove any added padding (if any, I'm not actually sure what's causing this), they're a bit further over than they should be I think.

Thanks as always!

![volume](https://user-images.githubusercontent.com/3939997/37914280-7a0fadcc-30dc-11e8-8513-769b63fd2567.png)

**Comment by jorti** [comment]
I have the same problem in Gnome 3.28.1 in Fedora 28.

Thanks for the extension.
