### ISSUE TITLE
Option to show volume percentage in top panel?

### ISSUE THREAD

**Issue by orschiro** [aleho/gnome-shell-volume-mixer#86]
Dear @aleho,

Would you find it useful, too, to add a feature showing the volume in percentage, similar to the battery percentage?

I would use it! :-)

Thanks!

![image](https://user-images.githubusercontent.com/170947/42552793-5b763fec-84de-11e8-92ef-7d6de23e8c4d.png)

**Comment by aleho** [comment]
No question, seems like a useful option.

**Comment by orschiro** [comment]
Cool, thanks for the positive and quick reply! :-) 

Is that fairly doable or complicated to implement?

**Comment by orschiro** [comment]
I placed a [bounty](https://www.bountysource.com/issues/58156022-option-to-show-volume-percentage-in-top-panel) for this.

**Comment by orschiro** [comment]
You may want to integrate [1](https://github.com/maestroschan/sound-percentage-gs-extension).

**Comment by Naveenaidu** [comment]
Dear @aleho I would like to work on this issue. Can you please point me in the right direction, Newcomer here :sweat_smile:
