### ISSUE TITLE
Visual shift on devices placing the extension on status menu.

### ISSUE THREAD

**Issue by jeukel** [aleho/gnome-shell-volume-mixer#87]
Placing the extension on the status menu, makes the devices shown to be visually shifted to the right almost one third of the panel. 

How do I help on debbugin?

Running Ubuntu 18.04.

**Comment by aleho** [comment]
Cloud you please provide a screenshot? Can't reproduce here.

**Comment by jeukel** [comment]
![Captura de pantalla de 2019-07-10 21-52-46](https://user-images.githubusercontent.com/4118593/61021104-4962ab80-a35d-11e9-8302-6bf2b9c2b64f.png)

**Comment by jeukel** [comment]
This is ubuntu 19.04. Shift has change in dimension but compared to the picture you have in the description, it looks shifted.

**Comment by aleho** [comment]
The shift is by design and I had a pretty good reason for it which I can't seem to remember any more. Something to do with aligning all the popup-menus and something being broken. ;)

Yes, the screenshot in this repo is outdated (will update ASAP).
